### PR TITLE
MRG: Use github actions for tests and expand platforms and versions

### PR DESCRIPTION
**Pull request by rob-luke**
Adds github tests. And also tests explicitly on 3 OSs and several julia versions.

I expect julia 1.0, 1.1, and 1.2 will fail as these are not supported by PortAudio, I will then remove these from the matrix.

### CODE REVIEW

**Comment by rob-luke** [comment]
@bramtayl This is ready for you to review and merge if you are happy. 

The appveyor is failing, but if you agree I will remove the appveyor and travis in a follow up PR? I find github actions easier to maintain and allows us to test different OSs, which is what appveyor and travis previous accomplished.

**Comment by bramtayl** [comment]
Looks good! I agree, lets ditch appveyor and travis if github can test on all platforms. Is there a reason not to test on 32-bit? Doesn't matter too much but would be easy to add. Out of curiosity, what's the timeout for?

**Comment by ssfrr** [comment]
Thanks for all this work! Makes me happy to see these packages revived a bit.

It’s a good idea to test on 32-but if possible. I’ve definitely caught bugs before due to the different integer sizing when interfacing to the C library.

**Comment by rob-luke** [comment]
> Is there a reason not to test on 32-bit? 

Added 😄. I prefer more testing, glad to add it.


> Out of curiosity, what's the timeout for?

Sometimes I've seen the CI get stuck in a stage (usually build). This will help it to fail, then you usually need to kick start it again manually. I set it several times larger than the usual run time.

> Thanks for all this work! Makes me happy to see these packages revived a bit.

Thank you for the lovely packages. Hopefully if we can assist with this _boring_ admin work it will encourage others to jump in too.

**Comment by rob-luke** [comment]
> I agree, lets ditch appveyor and travis if github can test on all platforms.

I will do this in a follow up PR. I find it easier to manage small individual steps, although it means it takes a bit longer.

**Pull request merged**
