### PR TITLE
add alsa_plugins

### PR DESCRIPTION
**Pull request by bramtayl**

### CODE REVIEW

**Comment by bramtayl** [comment]
Supersedes #55

**Comment by bramtayl** [comment]
Closes #42. Looks like a `get!` method `ENV` doesn't exist on older versions of Julia so we'll have to work around.

**Comment by rob-luke** [comment]
Thanks for the PR @bramtayl. I can see that you have requested a review from me. To review a PR I need to know what it is for and what it contains. So at a minimum to review it would be handy to include in the initial text field 1) what issue/bug/feature is this trying to achieve 2) what approach have you taken to solving it. As a bonus it helps to include 3) what are the considerations or pros/cons to the approach you have taken 4) what is an alternative option or what other information may be useful.

Including this information also helps when debugging issues in the future. When a bug is found it is convenient to use the `blame` function and see the commit/PR that it was associated with, and then to understand what was being done at the time.

These things may be obvious to you. But I am more of an auditory scientist that a computer scientist, so I'll just need a few extra helpers to sufficiently review your more technical PRs (the more detail the better). And I will try and run most of them locally to listen to them too.

**Comment by bramtayl** [comment]
Ok, sorry for the lack of explanation. Part of the problem is I'm not really a programmer, so I don't fully understand what is going on here either, but I'll give it a shot:

So on my version of Linux, the lower level software for interacting with the sound cards/drivers is ALSA, and the higher level software that does things like bluetooth support, networking, mixing, etc. is PulseAudio.

ALSA has an extension called ALSA plugins which allows it to interact with not just PulseAudio but a handful of other software too. However, in order to use the plugins, ALSA needs to know where to find the plugins. So this is just using an environmental variable to let ALSA know where to look for the plugins.

So on my computer, before this PR:

```
julia> PortAudio.devices()
7-element Vector{PortAudio.PortAudioDevice}:
 PortAudio.PortAudioDevice("sysdefault", "ALSA", 128, 128, 48000.0, 0, 0.021333333333333333, 0.021333333333333333, 0.021333333333333333, 0.021333333333333333)
 PortAudio.PortAudioDevice("front", "ALSA", 0, 2, 44100.0, 1, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("surround40", "ALSA", 0, 2, 44100.0, 2, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("surround51", "ALSA", 0, 2, 44100.0, 3, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("surround71", "ALSA", 0, 2, 44100.0, 4, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("hdmi", "ALSA", 0, 8, 44100.0, 5, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("dmix", "ALSA", 0, 2, 48000.0, 6, -1.0, 0.021333333333333333, -1.0, 0.021333333333333333)
```

After this PR:

```
julia> PortAudio.devices()
19-element Vector{PortAudio.PortAudioDevice}:
 PortAudio.PortAudioDevice("HDA Intel PCH: ALC295 Analog (hw:0,0)", "ALSA", 2, 2, 44100.0, 0, 0.005804988662131519, 0.005804988662131519, 0.034829931972789115, 0.034829931972789115)
 PortAudio.PortAudioDevice("HDA Intel PCH: HDMI 0 (hw:0,3)", "ALSA", 0, 8, 44100.0, 1, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("HDA Intel PCH: HDMI 1 (hw:0,7)", "ALSA", 0, 8, 44100.0, 2, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("HDA Intel PCH: HDMI 2 (hw:0,8)", "ALSA", 0, 8, 44100.0, 3, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("HDA Intel PCH: HDMI 3 (hw:0,9)", "ALSA", 0, 8, 44100.0, 4, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("HDA Intel PCH: HDMI 4 (hw:0,10)", "ALSA", 0, 8, 44100.0, 5, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("sysdefault", "ALSA", 128, 128, 48000.0, 6, 0.021333333333333333, 0.021333333333333333, 0.021333333333333333, 0.021333333333333333)
 PortAudio.PortAudioDevice("front", "ALSA", 0, 2, 44100.0, 7, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("surround40", "ALSA", 0, 2, 44100.0, 8, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("surround51", "ALSA", 0, 2, 44100.0, 9, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("surround71", "ALSA", 0, 2, 44100.0, 10, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("hdmi", "ALSA", 0, 8, 44100.0, 11, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("samplerate", "ALSA", 128, 128, 44100.0, 12, 0.007755102040816327, 0.007755102040816327, 0.023219954648526078, 0.023219954648526078)
 PortAudio.PortAudioDevice("speexrate", "ALSA", 128, 128, 44100.0, 13, 0.007755102040816327, 0.007755102040816327, 0.023219954648526078, 0.023219954648526078)
 PortAudio.PortAudioDevice("pulse", "ALSA", 32, 32, 44100.0, 14, 0.008684807256235827, 0.008684807256235827, 0.034807256235827665, 0.034807256235827665)
 PortAudio.PortAudioDevice("upmix", "ALSA", 8, 8, 44100.0, 15, 0.005804988662131519, 0.005804988662131519, 0.034829931972789115, 0.034829931972789115)
 PortAudio.PortAudioDevice("vdownmix", "ALSA", 6, 6, 44100.0, 16, 0.005804988662131519, 0.005804988662131519, 0.034829931972789115, 0.034829931972789115)
 PortAudio.PortAudioDevice("dmix", "ALSA", 0, 2, 48000.0, 17, -1.0, 0.021333333333333333, -1.0, 0.021333333333333333)
 PortAudio.PortAudioDevice("default", "ALSA", 32, 32, 44100.0, 18, 0.008684807256235827, 0.008684807256235827, 0.034807256235827665, 0.034807256235827665)
```

Additional notes:

- It's a little non-kosher to modify the environmental variables. So I considered only temporarily setting the variable when loading the package. However, the existing code already adds an environmental variable for the ALSA config file, so I figured this was fine for now.
- I buit both alsa_plugins_jll and PulseAudio_jll using BinaryBuilder. Both of them come with a bunch of optional dependencies, not all of which I was able to successfully build. Notably, I'm still working on getting bluetooth support into PulseAudio
- There's currently no way to test this with CI, because the linux buildbots don't seem to come with ALSA at all. Don't know if there's a way around this...

**Comment by bramtayl** [comment]
Also, side note, that I've never really collaborated on maintaining a repo and I'm still learning. So if you don't know how to review something, or don't have time, just let me know and I can merge, with consequences being on my head.

**Comment by rob-luke** [comment]
> Part of the problem is I'm not really a programmer, so I don't fully understand what is going on here either

No problem, we can learn together. Thanks for taking the time to write the detailed descriptions.

> with consequences being on my head

I understand your sentiment. But nothing is on your head, we are all just volunteers trying our best. Ill try and review as quickly as possible.

> I've never really collaborated on maintaining a repo and I'm still learning

For me the hardest part is always waiting for someone else to review code, I always want things instantly. But I think the benifits of collaboration outweight that negative. I'll just try and review as quick as I can.

**Comment by rob-luke** [comment]
@bramtayl thanks for the explanation.

I ran `PortAudio.devices()` on my linux lab pc using both master and this PR. I get the same output in both branches. Should this be the case? After I checked out your branch i ran `build PortAudio`, should I have done anything else?

**Comment by rob-luke** [comment]
image

**Comment by bramtayl** [comment]
Hmm, I wouldn't have expected them to be the same...

If you run 

```
using alsa_plugins_jll: alsa_plugins_jll
alsa_plugins_jll.is_available()
```

Do you get `true`?

**Comment by rob-luke** [comment]
> Do you get true?

Yes, see figure below. I get true and still the same 9 devices.

image

-------------------------

But to be pragmatic. This doesnt break anything for me. Yet it seems to fix something for you. So depends on your appetite to get to the bottom of that mystery, I am ok with pushing forward. So if you are ok with this I suggest we just ping @ssfr and see if he approves within a few days (he has said he is ok with us to administer, but nice to still provide him the option to chip in). But if we hear nothing within a week we merge.

**Comment by bramtayl** [comment]
I'm ok with merging too, but I think it would still be a good idea to figure out what's going on on your lab computer. So maybe if we merge, open a separate issue for that or something?

**Comment by rob-luke** [comment]
> So maybe if we merge, open a separate issue for that or something?

I use a funny OS, so I'm not too concerned. Lets wait a few days incase ssfr chimes in, and if not then go ahead and merge.

**Comment by ashwani-rathee** [comment]
Hey there, I also want to help in the developement of portaudio.jl. I also tried the same thing as rob-luke and was able to get a 19 element vector..
```julia

julia> using PortAudio
[ Info: Precompiling PortAudio [80ea8bcb-4634-5cb3-8ee8-a132660d1d2d]

julia> PortAudio.devices()
19-element Vector{PortAudio.PortAudioDevice}:
 PortAudio.PortAudioDevice("HDA Intel PCH: ALC236 Analog (hw:0,0)", "ALSA", 2, 2, 44100.0, 0, 0.005804988662131519, 0.005804988662131519, 0.034829931972789115, 0.034829931972789115)
 PortAudio.PortAudioDevice("HDA Intel PCH: HDMI 0 (hw:0,3)", "ALSA", 0, 8, 44100.0, 1, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("HDA Intel PCH: HDMI 1 (hw:0,7)", "ALSA", 0, 8, 44100.0, 2, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("HDA Intel PCH: HDMI 2 (hw:0,8)", "ALSA", 0, 8, 44100.0, 3, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("HDA Intel PCH: HDMI 3 (hw:0,9)", "ALSA", 0, 8, 44100.0, 4, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("HDA Intel PCH: HDMI 4 (hw:0,10)", "ALSA", 0, 8, 44100.0, 5, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 ⋮
 PortAudio.PortAudioDevice("pulse", "ALSA", 32, 32, 44100.0, 14, 0.008684807256235827, 0.008684807256235827, 0.034807256235827665, 0.034807256235827665)
 PortAudio.PortAudioDevice("upmix", "ALSA", 8, 8, 44100.0, 15, 0.005804988662131519, 0.005804988662131519, 0.034829931972789115, 0.034829931972789115)
 PortAudio.PortAudioDevice("vdownmix", "ALSA", 6, 6, 44100.0, 16, 0.005804988662131519, 0.005804988662131519, 0.034829931972789115, 0.034829931972789115)
 PortAudio.PortAudioDevice("dmix", "ALSA", 0, 2, 48000.0, 17, -1.0, 0.021333333333333333, -1.0, 0.021333333333333333)
 PortAudio.PortAudioDevice("default", "ALSA", 32, 32, 44100.0, 18, 0.008684807256235827, 0.008684807256235827, 0.034807256235827665, 0.034807256235827665)

julia> using alsa_plugins_jll: alsa_plugins_jll

julia> alsa_plugins_jll.is_available()
true

```

**Comment by rob-luke** [comment]
Thanks @ashwani-rathee!
How many devices where reported if you did not use this branch with alsa_plugin?

**Comment by ashwani-rathee** [comment]
It's a 8 element vector then:
```julia
julia> PortAudio.devices()
8-element Vector{PortAudio.PortAudioDevice}:
 PortAudio.PortAudioDevice("sysdefault", "ALSA", 128, 128, 48000.0, 0, 0.021333333333333333, 0.021333333333333333, 0.021333333333333333, 0.021333333333333333)
 PortAudio.PortAudioDevice("front", "ALSA", 0, 2, 44100.0, 1, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("surround40", "ALSA", 0, 2, 44100.0, 2, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("surround51", "ALSA", 0, 2, 44100.0, 3, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("surround71", "ALSA", 0, 2, 44100.0, 4, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("hdmi", "ALSA", 0, 8, 44100.0, 5, -1.0, 0.005804988662131519, -1.0, 0.034829931972789115)
 PortAudio.PortAudioDevice("default", "ALSA", 128, 128, 48000.0, 6, 0.021333333333333333, 0.021333333333333333, 0.021333333333333333, 0.021333333333333333)
 PortAudio.PortAudioDevice("dmix", "ALSA", 0, 2, 48000.0, 7, -1.0, 0.021333333333333333, -1.0, 0.021333333333333333)


```

**Review by rob-luke — APPROVED** [review]
Thanks @ashwani-rathee . So this looks good to merge @bramtayl

**Comment by bramtayl** [comment]
Sweet! Welcome @ashwani-rathee ! Help is greatly appreciated!

**Pull request merged**
