### PR TITLE
exposed pa stream latency

### PR DESCRIPTION
**Pull request by jakubwro**
Hi, I exposed latency.
These docs say that there is a device property for  latency http://portaudio.com/docs/v19-doxydocs/blocking_read_write.html

`Pa_GetDeviceInfo( inputParameters.device )->defaultHighOutputLatency`

Shouldn't we use that? For instance we can avoid specifying values, but only symbols (or enum) `latency=:low` `latency=:high`, and choose between `defaultHighOutputLatency` and `defaultLowOutputLatency` for a device.

### CODE REVIEW

**Comment by jakubwro** [comment]
I added a script to measure actual latency. Before run put your headphones near to the microphone.

My system results are quite similar to what I measured previously with a stopwatch.

```
505 ms latency for in_latency=0.1, out_latency=0.1, blocksize=32
199 ms latency for in_latency=0.1, out_latency=0.01, blocksize=32
765 ms latency for in_latency=0.1, out_latency=0.005, blocksize=32
485 ms latency for in_latency=0.01, out_latency=0.1, blocksize=32
62 ms latency for in_latency=0.01, out_latency=0.01, blocksize=32
57 ms latency for in_latency=0.01, out_latency=0.005, blocksize=32
435 ms latency for in_latency=0.005, out_latency=0.1, blocksize=32
46 ms latency for in_latency=0.005, out_latency=0.01, blocksize=32
4 ms latency for in_latency=0.005, out_latency=0.005, blocksize=32
```

**Comment by ssfrr** [comment]
This is great, thanks. I’ll merge soon once I get to my computer and can test it out. On your machine are you able to do audio processing at low latencies without dropouts?

**Comment by jakubwro** [comment]
> This is great, thanks. I’ll merge soon once I get to my computer and can test it out. On your machine are you able to do audio processing at low latencies without dropouts?

I think so, for `latency=0.009` I cannot hear them. for `0.005-0.003` they can occur sometimes. For `latency=0.002` dropouts are massive. For my device I can see low latency default is `0.017` so I can go much lower than that. It's 2013 macbook pro.

**Comment by ssfrr** [comment]
@jakubwro I mentioned this in the other issue but it might be easier to handle it here - do you find that you need to set the blocksize in addition to the latency, or can you just set latency and let PortAudio figure out what blocksize to use (by setting `blocksize` to `0`)? The PortAudio docs strongly suggest only setting the blocksize when you really need to, and I think because we're using the read/write API it shouldn't matter to the application. Basically I'm considering whether we just want to always set the blocksize ("`framesPerBuffer`" in the portaudio docs) to `0` when we create the device, so it's less confusing to the caller.

For applications that want to really push their latency we could still implement `blocksize(stream)` to allow you to read out the block size that the underlying device is using, but it's not clear to me that it needs to be settable when opening a stream.

**Comment by jakubwro** [comment]
> For applications that want to really push their latency we could still implement `blocksize(stream)` to allow you to read out the block size that the underlying device is using, but it's not clear to me that it needs to be settable when opening a stream.

Right, it should be set to 0 when latency is specified I have no access to my computer right now, I will change it tomorrow and do testing.

**Comment by jakubwro** [comment]
I opened #43, let's close this one without merge.

**Pull request closed without merging**
