### PR TITLE
Compat Julia 0.7

### PR DESCRIPTION
**Pull request by wookay**
Compat 0.66.0 for `fetch`, `@cfunction`

### CODE REVIEW

**Comment by ssfrr** [comment]
`master` is now compatible with 0.7 and 1.0

**Comment by ssfrr** [comment]
whoops, a little hasty on that. I thought these changes were already merged. soon.

**Comment by ssfrr** [comment]
closing in favor of #40

**Comment by ssfrr** [comment]
Thanks for this! I've incorporated it into #40 so these commits will be merged when that is.

**Comment by wookay** [comment]
thanks all

**Pull request closed without merging**
