### PR TITLE
Allow skipping locks, precompile

### PR DESCRIPTION
**Pull request by bramtayl**
I added a Bool keyword argument to` write_buffer and read_buffer to allow skipping the lock. This is useful to speed up performance in places where you know no other thread is going to be reading or writing to the buffer. I also added a handful of precompilation statements for some front-end and/or important functions.

### CODE REVIEW

**Comment by bramtayl** [comment]
@JuliaRegistrator register

**Comment by bramtayl** [comment]
@JuliaRegistrator register

**Review by bramtayl — COMMENTED** [review]
@JuliaRegistrator register

**Comment by JeffFessler** [comment]
Sorry for slow response - I was traveling with no wifi recently.
I don't know enough about `lock` to comment on these changes.

**Comment by bramtayl** [comment]
No problem! Locks are still on be default, so I think this is still fairly safe.

**Pull request merged**
