### PR TITLE
[WIP] Julia v1 support and usage of BB builder for libportaudio

### PR DESCRIPTION
**Pull request by jpsamaroo**
Builds on top of the `julia1` branch, hence all the commits. I plan to try my hand at making a BB builder for pa_shim as well.

EDIT: Requires something like https://github.com/JuliaAudio/RingBuffers.jl/pull/14 for Julia 1.2+ support.

### CODE REVIEW

**Comment by kleinschmidt** [comment]
Any progress on this?  I'd like to update to a mainline (or preferably released) version if possible...

**Comment by jpsamaroo** [comment]
I don't have the time to work on this right now, but it's pretty much just a matter of getting PortAudioBuilder working on all platforms, and then getting CI happy. The last Travis run had a single passing build on Julia 1.0, which means we're almost there.

**Comment by ssfrr** [comment]
I've incorporated @jpsamaroo and @staticfloat's work, as well as some other improvements into the `nocallback` branch. There's now a builder for libportaudio in Yggdrasil, so we don't need PortAudioBuilder anymore. I've also re-worked the low-level interface to portaudio so that I don't need the C shim any more, and the whole interface is much simpler, and not longer dependent on RingBuffers.jl (I'll probably retire that package). This should greatly reduce the number of library loading issues that have popped up on various people's machines.

Maybe check the `nocallback` branch out and see if it's working for you. If so I think it's a strict improvement over the current situation, so I may just merge and tag a release even though there are things I still want to do.

**Comment by ssfrr** [comment]
closing in favor of #40

**Pull request closed without merging**
