### PR TITLE
Add audio signal output example

### PR DESCRIPTION
**Pull request by JeffFessler**
It took me a while to figure this out so perhaps this example could save others time.

### CODE REVIEW

**Comment by bramtayl** [comment]
Thanks! What was it that took you a while to figure out? The unit conversions? Those are tricky, it would be nice if SampledSignals used Unitful quantities.

**Comment by JeffFessler** [comment]
> What was it that took you a while to figure out?

That `write` could accept both a stream argument and an array.
Every example with `write` in the README currently has `write(stream, stream)` which does not convey the possibility of `write(stream, data)`.  I don't remember what made me decide to take the leap and just try it anyway...

**Comment by rob-luke** [comment]
@bramtayl would these examples be better as actual scripts rather than in the readme? The benifit of putting them as scripts in the examples folder is that they could be tested more easily both locally and on the CI. Thoughts?

**Comment by bramtayl** [comment]
Seems like @JeffFessler looked to the README first, so that's where it should go. There's already code in the README, we just need to make sure to test all the code in the README periodically (or else write some kind of script to do it in CI or part of doctests?). I think this example would be clearer if it used more SampledSignals infrastructure (`SampleBuf`, and maybe also `SinSource`).

**Comment by JeffFessler** [comment]
Because the READMe already had several helpful examples (but not the simple one I needed), I had not noticed the examples/ directory!  The examples in the README are similarly concise and have descriptive headers.  The files in the examples/ directory have very few comments and some lack any descriptive header comment that would make them more useful.  I personally like Literate for showing examples, but I'm not sure if that works well for audio code like it does for images (my main focus).

**Comment by JeffFessler** [comment]
bump :)

**Comment by JeffFessler** [comment]
bump again.  I am teaching a music signal processing class with 79 freshman and having more docs and examples in the README can only help.
in the long run if someone wants to put more documented examples in the examples directory that's fine but maybe this simple addition to the readme would be ok for now?

**Comment by bramtayl** [comment]
Hi Jeff. That's great are you using the package for the class? Sure, I can merge this. I still think there's something to be said about using SampleBuf but.

**Comment by bramtayl** [comment]
PS I've been working on getting code in the example folder running and am running into trouble with the ones using Makie. Could be a fun project for students.

**Pull request merged**
